import Foundation

enum MatchGameCategory: Sendable {
    case emotions
    case food
    case travel
    case places
    case objects
    case animals
    case uncategorized
}

struct MatchGameItem: Identifiable, Equatable, Sendable {
    let id: String
    let italian: String
    let spanish: String
    let imageName: String
    let placeholder: String
    let systemImageName: String?
    let category: MatchGameCategory

    init(
        id: String,
        italian: String,
        spanish: String,
        imageName: String,
        placeholder: String,
        systemImageName: String? = nil,
        category: MatchGameCategory = .uncategorized
    ) {
        self.id = id
        self.italian = italian
        self.spanish = spanish
        self.imageName = imageName
        self.placeholder = placeholder
        self.systemImageName = systemImageName
        self.category = category
    }
}

struct MatchGameRound: Equatable, Sendable {
    let item: MatchGameItem
    let choices: [String]
}

enum MatchGameCatalog {
    static let items = categorized(emotions, as: .emotions)
        + categorized(food, as: .food)
        + categorized(travel, as: .travel)
        + categorized(places, as: .places)
        + categorized(objects, as: .objects)
        + categorized(animals, as: .animals)

    private static func categorized(
        _ items: [MatchGameItem],
        as category: MatchGameCategory
    ) -> [MatchGameItem] {
        items.map { item in
            MatchGameItem(
                id: item.id,
                italian: item.italian,
                spanish: item.spanish,
                imageName: item.imageName,
                placeholder: item.placeholder,
                systemImageName: item.systemImageName,
                category: category
            )
        }
    }

    private static let emotions: [MatchGameItem] = [
        MatchGameItem(id: "felice", italian: "felice", spanish: "feliz", imageName: "game_felice", placeholder: "😄"),
        MatchGameItem(id: "triste", italian: "triste", spanish: "triste", imageName: "game_triste", placeholder: "😢"),
        MatchGameItem(id: "arrabbiato", italian: "arrabbiato", spanish: "enfadado", imageName: "game_arrabbiato", placeholder: "😠"),
        MatchGameItem(id: "sorpreso", italian: "sorpreso", spanish: "sorprendido", imageName: "game_sorpreso", placeholder: "😮"),
        MatchGameItem(id: "spaventato", italian: "spaventato", spanish: "asustado", imageName: "game_spaventato", placeholder: "😨"),
        MatchGameItem(id: "stanco", italian: "stanco", spanish: "cansado", imageName: "game_stanco", placeholder: "😴💤"),
        MatchGameItem(id: "confuso", italian: "confuso", spanish: "confundido", imageName: "game_confuso", placeholder: "😕"),
        MatchGameItem(id: "innamorato", italian: "innamorato", spanish: "enamorado", imageName: "game_innamorato", placeholder: "😍"),
        MatchGameItem(id: "annoiato", italian: "annoiato", spanish: "aburrido", imageName: "game_annoiato", placeholder: "😑"),
        MatchGameItem(id: "preoccupato", italian: "preoccupato", spanish: "preocupado", imageName: "game_preoccupato", placeholder: "😟💭"),
        MatchGameItem(id: "sereno", italian: "sereno", spanish: "sereno", imageName: "game_sereno", placeholder: "😌☀️"),
        MatchGameItem(id: "entusiasta", italian: "entusiasta", spanish: "entusiasmado", imageName: "game_entusiasta", placeholder: "🤩"),
        MatchGameItem(id: "orgoglioso", italian: "orgoglioso", spanish: "orgulloso", imageName: "game_orgoglioso", placeholder: "😏"),
        MatchGameItem(id: "timido", italian: "timido", spanish: "tímido", imageName: "game_timido", placeholder: "😊🙈"),
        MatchGameItem(id: "geloso", italian: "geloso", spanish: "celoso", imageName: "game_geloso", placeholder: "😒"),
        MatchGameItem(id: "nervoso", italian: "nervoso", spanish: "nervioso", imageName: "game_nervoso", placeholder: "😬"),
        MatchGameItem(id: "deluso", italian: "deluso", spanish: "decepcionado", imageName: "game_deluso", placeholder: "😞💔"),
        MatchGameItem(id: "sollevato", italian: "sollevato", spanish: "aliviado", imageName: "game_sollevato", placeholder: "😌💨"),
        MatchGameItem(id: "curioso", italian: "curioso", spanish: "curioso", imageName: "game_curioso", placeholder: "🤔🔍"),
        MatchGameItem(id: "imbarazzato", italian: "imbarazzato", spanish: "avergonzado", imageName: "game_imbarazzato", placeholder: "😳"),
        MatchGameItem(id: "fiducioso", italian: "fiducioso", spanish: "confiado", imageName: "game_fiducioso", placeholder: "😎"),
        MatchGameItem(id: "speranzoso", italian: "speranzoso", spanish: "esperanzado", imageName: "game_speranzoso", placeholder: "🙏"),
        MatchGameItem(id: "grato", italian: "grato", spanish: "agradecido", imageName: "game_grato", placeholder: "🥹🙏"),
        MatchGameItem(id: "solo", italian: "solo", spanish: "solo", imageName: "game_solo", placeholder: "😔👤"),
        MatchGameItem(id: "malinconico", italian: "malinconico", spanish: "melancólico", imageName: "game_malinconico", placeholder: "😔🌧️"),
        MatchGameItem(id: "divertito", italian: "divertito", spanish: "divertido", imageName: "game_divertito", placeholder: "😆"),
        MatchGameItem(id: "disgustato", italian: "disgustato", spanish: "asqueado", imageName: "game_disgustato", placeholder: "🤢"),
        MatchGameItem(id: "soddisfatto", italian: "soddisfatto", spanish: "satisfecho", imageName: "game_soddisfatto", placeholder: "😊✅"),
        MatchGameItem(id: "impaziente", italian: "impaziente", spanish: "impaciente", imageName: "game_impaziente", placeholder: "⏳"),
        MatchGameItem(id: "rilassato", italian: "rilassato", spanish: "relajado", imageName: "game_rilassato", placeholder: "😌🧘"),
        MatchGameItem(id: "concentrato", italian: "concentrato", spanish: "concentrado", imageName: "game_concentrato", placeholder: "🧐"),
        MatchGameItem(id: "coraggioso", italian: "coraggioso", spanish: "valiente", imageName: "game_coraggioso", placeholder: "🦸"),
        MatchGameItem(id: "insicuro", italian: "insicuro", spanish: "inseguro", imageName: "game_insicuro", placeholder: "😟❓"),
        MatchGameItem(id: "motivato", italian: "motivato", spanish: "motivado", imageName: "game_motivato", placeholder: "💪"),
        MatchGameItem(id: "scoraggiato", italian: "scoraggiato", spanish: "desanimado", imageName: "game_scoraggiato", placeholder: "😞⬇️"),
        MatchGameItem(id: "commosso", italian: "commosso", spanish: "conmovido", imageName: "game_commosso", placeholder: "🥹❤️"),
        MatchGameItem(id: "offeso", italian: "offeso", spanish: "ofendido", imageName: "game_offeso", placeholder: "😤💢"),
        MatchGameItem(id: "colpevole", italian: "colpevole", spanish: "culpable", imageName: "game_colpevole", placeholder: "😓"),
        MatchGameItem(id: "sospettoso", italian: "sospettoso", spanish: "sospechoso", imageName: "game_sospettoso", placeholder: "🤨"),
        MatchGameItem(id: "perplesso", italian: "perplesso", spanish: "perplejo", imageName: "game_perplesso", placeholder: "🤔❓"),
        MatchGameItem(id: "euforico", italian: "euforico", spanish: "eufórico", imageName: "game_euforico", placeholder: "🥳"),
        MatchGameItem(id: "contento", italian: "contento", spanish: "contento", imageName: "game_contento", placeholder: "🙂"),
        MatchGameItem(id: "furioso", italian: "furioso", spanish: "furioso", imageName: "game_furioso", placeholder: "🤬"),
        MatchGameItem(id: "terrorizzato", italian: "terrorizzato", spanish: "aterrorizado", imageName: "game_terrorizzato", placeholder: "😱"),
        MatchGameItem(id: "addormentato", italian: "addormentato", spanish: "dormido", imageName: "game_addormentato", placeholder: "😴🛏️"),
        MatchGameItem(id: "sconvolto", italian: "sconvolto", spanish: "conmocionado", imageName: "game_sconvolto", placeholder: "😵"),
        MatchGameItem(id: "premuroso", italian: "premuroso", spanish: "cariñoso", imageName: "game_premuroso", placeholder: "🤗"),
        MatchGameItem(id: "indifferente", italian: "indifferente", spanish: "indiferente", imageName: "game_indifferente", placeholder: "😐"),
        MatchGameItem(id: "nostalgico", italian: "nostalgico", spanish: "nostálgico", imageName: "game_nostalgico", placeholder: "🥲"),
        MatchGameItem(id: "determinato", italian: "determinato", spanish: "decidido", imageName: "game_determinato", placeholder: "😤🎯"),
    ]

    private static let food: [MatchGameItem] = [
        MatchGameItem(id: "mela", italian: "mela", spanish: "manzana", imageName: "game_mela", placeholder: "🍎"),
        MatchGameItem(id: "banana", italian: "banana", spanish: "banana", imageName: "game_banana", placeholder: "🍌"),
        MatchGameItem(id: "pane", italian: "pane", spanish: "pan", imageName: "game_pane", placeholder: "🍞"),
        MatchGameItem(id: "caffe", italian: "caffè", spanish: "café", imageName: "game_caffe", placeholder: "☕️🫘"),
        MatchGameItem(id: "acqua", italian: "acqua", spanish: "agua", imageName: "game_acqua", placeholder: "💧"),
        MatchGameItem(id: "pizza", italian: "pizza", spanish: "pizza", imageName: "game_pizza", placeholder: "🍕"),
        MatchGameItem(id: "pasta", italian: "pasta", spanish: "pasta", imageName: "game_pasta", placeholder: "🍝"),
        MatchGameItem(id: "formaggio", italian: "formaggio", spanish: "queso", imageName: "game_formaggio", placeholder: "🧀"),
        MatchGameItem(id: "gelato", italian: "gelato", spanish: "helado", imageName: "game_gelato", placeholder: "🍨"),
        MatchGameItem(id: "uovo", italian: "uovo", spanish: "huevo", imageName: "game_uovo", placeholder: "🥚"),
        MatchGameItem(id: "arancia", italian: "arancia", spanish: "naranja", imageName: "game_arancia", placeholder: "🍊"),
        MatchGameItem(id: "limone", italian: "limone", spanish: "limón", imageName: "game_limone", placeholder: "🍋"),
        MatchGameItem(id: "fragola", italian: "fragola", spanish: "fresa", imageName: "game_fragola", placeholder: "🍓"),
        MatchGameItem(id: "uva", italian: "uva", spanish: "uva", imageName: "game_uva", placeholder: "🍇"),
        MatchGameItem(id: "anguria", italian: "anguria", spanish: "sandía", imageName: "game_anguria", placeholder: "🍉"),
        MatchGameItem(id: "pera", italian: "pera", spanish: "pera", imageName: "game_pera", placeholder: "🍐"),
        MatchGameItem(id: "pesca", italian: "pesca", spanish: "melocotón", imageName: "game_pesca", placeholder: "🍑"),
        MatchGameItem(id: "ciliegia", italian: "ciliegia", spanish: "cereza", imageName: "game_ciliegia", placeholder: "🍒"),
        MatchGameItem(id: "ananas", italian: "ananas", spanish: "piña", imageName: "game_ananas", placeholder: "🍍"),
        MatchGameItem(id: "kiwi", italian: "kiwi", spanish: "kiwi", imageName: "game_kiwi", placeholder: "🥝"),
        MatchGameItem(id: "pomodoro", italian: "pomodoro", spanish: "tomate", imageName: "game_pomodoro", placeholder: "🍅"),
        MatchGameItem(id: "carota", italian: "carota", spanish: "zanahoria", imageName: "game_carota", placeholder: "🥕"),
        MatchGameItem(id: "mais", italian: "mais", spanish: "maíz", imageName: "game_mais", placeholder: "🌽"),
        MatchGameItem(id: "patata", italian: "patata", spanish: "patata", imageName: "game_patata", placeholder: "🥔"),
        MatchGameItem(id: "cipolla", italian: "cipolla", spanish: "cebolla", imageName: "game_cipolla", placeholder: "🧅"),
        MatchGameItem(id: "aglio", italian: "aglio", spanish: "ajo", imageName: "game_aglio", placeholder: "🧄"),
        MatchGameItem(id: "broccoli", italian: "broccoli", spanish: "brócoli", imageName: "game_broccoli", placeholder: "🥦"),
        MatchGameItem(id: "insalata", italian: "insalata", spanish: "ensalada", imageName: "game_insalata", placeholder: "🥗"),
        MatchGameItem(id: "riso", italian: "riso", spanish: "arroz", imageName: "game_riso", placeholder: "🍚"),
        MatchGameItem(id: "minestra", italian: "minestra", spanish: "sopa", imageName: "game_minestra", placeholder: "🍲🥣"),
        MatchGameItem(id: "carne", italian: "carne", spanish: "carne", imageName: "game_carne", placeholder: "🥩"),
        MatchGameItem(id: "pollo", italian: "pollo", spanish: "pollo", imageName: "game_pollo", placeholder: "🍗"),
        MatchGameItem(id: "salmone", italian: "salmone", spanish: "salmón", imageName: "game_salmone", placeholder: "🐟🍽️"),
        MatchGameItem(id: "prosciutto", italian: "prosciutto", spanish: "jamón", imageName: "game_prosciutto", placeholder: "🥓"),
        MatchGameItem(id: "salsiccia", italian: "salsiccia", spanish: "salchicha", imageName: "game_salsiccia", placeholder: "🌭"),
        MatchGameItem(id: "hamburger", italian: "hamburger", spanish: "hamburguesa", imageName: "game_hamburger", placeholder: "🍔"),
        MatchGameItem(id: "panino", italian: "panino", spanish: "bocadillo", imageName: "game_panino", placeholder: "🥪"),
        MatchGameItem(id: "lasagna", italian: "lasagna", spanish: "lasaña", imageName: "game_lasagna", placeholder: "🍝🧀"),
        MatchGameItem(id: "biscotto", italian: "biscotto", spanish: "galleta", imageName: "game_biscotto", placeholder: "🍪"),
        MatchGameItem(id: "torta", italian: "torta", spanish: "tarta", imageName: "game_torta", placeholder: "🍰"),
        MatchGameItem(id: "cioccolato", italian: "cioccolato", spanish: "chocolate", imageName: "game_cioccolato", placeholder: "🍫"),
        MatchGameItem(id: "miele", italian: "miele", spanish: "miel", imageName: "game_miele", placeholder: "🍯"),
        MatchGameItem(id: "latte", italian: "latte", spanish: "leche", imageName: "game_latte", placeholder: "🥛🐄"),
        MatchGameItem(id: "te", italian: "tè", spanish: "té", imageName: "game_te", placeholder: "🍵"),
        MatchGameItem(id: "succo", italian: "succo", spanish: "zumo", imageName: "game_succo", placeholder: "🧃"),
        MatchGameItem(id: "vino", italian: "vino", spanish: "vino", imageName: "game_vino", placeholder: "🍷"),
        MatchGameItem(id: "birra", italian: "birra", spanish: "cerveza", imageName: "game_birra", placeholder: "🍺"),
        MatchGameItem(id: "burro", italian: "burro", spanish: "mantequilla", imageName: "game_burro", placeholder: "🧈"),
        MatchGameItem(id: "sale", italian: "sale", spanish: "sal", imageName: "game_sale", placeholder: "🧂"),
        MatchGameItem(id: "zucchero", italian: "zucchero", spanish: "azúcar", imageName: "game_zucchero", placeholder: "🧂🍬"),
    ]

    private static let travel: [MatchGameItem] = [
        MatchGameItem(id: "auto", italian: "auto", spanish: "coche", imageName: "game_auto", placeholder: "🚗"),
        MatchGameItem(id: "treno", italian: "treno", spanish: "tren", imageName: "game_treno", placeholder: "🚆"),
        MatchGameItem(id: "bicicletta", italian: "bicicletta", spanish: "bicicleta", imageName: "game_bicicletta", placeholder: "🚲"),
        MatchGameItem(id: "autobus", italian: "autobus", spanish: "autobús", imageName: "game_autobus", placeholder: "🚌"),
        MatchGameItem(id: "aereo", italian: "aereo", spanish: "avión", imageName: "game_aereo", placeholder: "✈️"),
        MatchGameItem(id: "nave", italian: "nave", spanish: "barco", imageName: "game_nave", placeholder: "🚢"),
        MatchGameItem(id: "valigia", italian: "valigia", spanish: "maleta", imageName: "game_valigia", placeholder: "🧳"),
        MatchGameItem(id: "passaporto", italian: "passaporto", spanish: "pasaporte", imageName: "game_passaporto", placeholder: "🛂📘"),
        MatchGameItem(id: "biglietto", italian: "biglietto", spanish: "billete", imageName: "game_biglietto", placeholder: "🎫"),
        MatchGameItem(id: "mappa", italian: "mappa", spanish: "mapa", imageName: "game_mappa", placeholder: "🗺️"),
        MatchGameItem(id: "taxi", italian: "taxi", spanish: "taxi", imageName: "game_taxi", placeholder: "🚕"),
        MatchGameItem(id: "metropolitana", italian: "metropolitana", spanish: "metro", imageName: "game_metropolitana", placeholder: "🚇🏙️"),
        MatchGameItem(id: "tram", italian: "tram", spanish: "tranvía", imageName: "game_tram", placeholder: "🚊"),
        MatchGameItem(id: "motocicletta", italian: "motocicletta", spanish: "motocicleta", imageName: "game_motocicletta", placeholder: "🏍️"),
        MatchGameItem(id: "scooter", italian: "scooter", spanish: "escúter", imageName: "game_scooter", placeholder: "🛵"),
        MatchGameItem(id: "camion", italian: "camion", spanish: "camión", imageName: "game_camion", placeholder: "🚚"),
        MatchGameItem(id: "traghetto", italian: "traghetto", spanish: "ferri", imageName: "game_traghetto", placeholder: "⛴️"),
        MatchGameItem(id: "elicottero", italian: "elicottero", spanish: "helicóptero", imageName: "game_elicottero", placeholder: "🚁"),
        MatchGameItem(id: "razzo", italian: "razzo", spanish: "cohete", imageName: "game_razzo", placeholder: "🚀"),
        MatchGameItem(id: "funivia", italian: "funivia", spanish: "teleférico", imageName: "game_funivia", placeholder: "🚠"),
        MatchGameItem(id: "camper", italian: "camper", spanish: "autocaravana", imageName: "game_camper", placeholder: "🚐🏕️"),
        MatchGameItem(id: "roulotte", italian: "roulotte", spanish: "caravana", imageName: "game_roulotte", placeholder: "🚐🛏️"),
        MatchGameItem(id: "canoa", italian: "canoa", spanish: "canoa", imageName: "game_canoa", placeholder: "🛶"),
        MatchGameItem(id: "barca", italian: "barca", spanish: "velero", imageName: "game_barca", placeholder: "⛵"),
        MatchGameItem(id: "porto", italian: "porto", spanish: "puerto", imageName: "game_porto", placeholder: "⚓"),
        MatchGameItem(id: "fermata", italian: "fermata", spanish: "parada", imageName: "game_fermata", placeholder: "🚏"),
        MatchGameItem(id: "binario", italian: "binario", spanish: "andén", imageName: "game_binario", placeholder: "🛤️"),
        MatchGameItem(id: "strada", italian: "strada", spanish: "carretera", imageName: "game_strada", placeholder: "🛣️"),
        MatchGameItem(id: "autostrada", italian: "autostrada", spanish: "autopista", imageName: "game_autostrada", placeholder: "🛣️🚗"),
        MatchGameItem(id: "ponte", italian: "ponte", spanish: "puente", imageName: "game_ponte", placeholder: "🌉"),
        MatchGameItem(id: "tunnel", italian: "tunnel", spanish: "túnel", imageName: "game_tunnel", placeholder: "🚇➡️"),
        MatchGameItem(id: "semaforo", italian: "semaforo", spanish: "semáforo", imageName: "game_semaforo", placeholder: "🚦"),
        MatchGameItem(id: "benzina", italian: "benzina", spanish: "gasolina", imageName: "game_benzina", placeholder: "⛽"),
        MatchGameItem(id: "parcheggio", italian: "parcheggio", spanish: "aparcamiento", imageName: "game_parcheggio", placeholder: "🅿️"),
        MatchGameItem(id: "frontiera", italian: "frontiera", spanish: "frontera", imageName: "game_frontiera", placeholder: "🛂🚧"),
        MatchGameItem(id: "dogana", italian: "dogana", spanish: "aduana", imageName: "game_dogana", placeholder: "🛃"),
        MatchGameItem(id: "bagaglio", italian: "bagaglio", spanish: "equipaje", imageName: "game_bagaglio", placeholder: "🧳✈️"),
        MatchGameItem(id: "zaino", italian: "zaino", spanish: "mochila", imageName: "game_zaino", placeholder: "🎒"),
        MatchGameItem(id: "bussola", italian: "bussola", spanish: "brújula", imageName: "game_bussola", placeholder: "🧭"),
        MatchGameItem(id: "guida", italian: "guida", spanish: "guía", imageName: "game_guida", placeholder: "🧑‍✈️📍"),
        MatchGameItem(id: "turista", italian: "turista", spanish: "turista", imageName: "game_turista", placeholder: "📸"),
        MatchGameItem(id: "pilota", italian: "pilota", spanish: "piloto", imageName: "game_pilota", placeholder: "🧑‍✈️✈️"),
        MatchGameItem(id: "capitano", italian: "capitano", spanish: "capitán", imageName: "game_capitano", placeholder: "🧑‍✈️⚓"),
        MatchGameItem(id: "viaggio", italian: "viaggio", spanish: "viaje", imageName: "game_viaggio", placeholder: "🌍"),
        MatchGameItem(id: "vacanza", italian: "vacanza", spanish: "vacaciones", imageName: "game_vacanza", placeholder: "🏖️🧳"),
        MatchGameItem(id: "partenza", italian: "partenza", spanish: "salida", imageName: "game_partenza", placeholder: "🛫➡️"),
        MatchGameItem(id: "arrivo", italian: "arrivo", spanish: "llegada", imageName: "game_arrivo", placeholder: "🛬"),
        MatchGameItem(id: "prenotazione", italian: "prenotazione", spanish: "reserva", imageName: "game_prenotazione", placeholder: "📝"),
        MatchGameItem(id: "campeggio", italian: "campeggio", spanish: "camping", imageName: "game_campeggio", placeholder: "🏕️"),
        MatchGameItem(id: "itinerario", italian: "itinerario", spanish: "itinerario", imageName: "game_itinerario", placeholder: "🗺️📍"),
    ]

    private static let places: [MatchGameItem] = [
        MatchGameItem(id: "casa", italian: "casa", spanish: "casa", imageName: "game_casa", placeholder: "🏠"),
        MatchGameItem(id: "scuola", italian: "scuola", spanish: "escuela", imageName: "game_scuola", placeholder: "🏫"),
        MatchGameItem(id: "ospedale", italian: "ospedale", spanish: "hospital", imageName: "game_ospedale", placeholder: "🏥"),
        MatchGameItem(id: "stazione", italian: "stazione", spanish: "estación", imageName: "game_stazione", placeholder: "🚉"),
        MatchGameItem(id: "aeroporto", italian: "aeroporto", spanish: "aeropuerto", imageName: "game_aeroporto", placeholder: "🛫🏢"),
        MatchGameItem(id: "ristorante", italian: "ristorante", spanish: "restaurante", imageName: "game_ristorante", placeholder: "🏠🍽️"),
        MatchGameItem(id: "albergo", italian: "albergo", spanish: "hotel", imageName: "game_albergo", placeholder: "🏨"),
        MatchGameItem(id: "spiaggia", italian: "spiaggia", spanish: "playa", imageName: "game_spiaggia", placeholder: "🏖️"),
        MatchGameItem(id: "montagna", italian: "montagna", spanish: "montaña", imageName: "game_montagna", placeholder: "🏔️"),
        MatchGameItem(id: "parco", italian: "parco", spanish: "parque", imageName: "game_parco", placeholder: "🌳🛝"),
        MatchGameItem(id: "ufficio", italian: "ufficio", spanish: "oficina", imageName: "game_ufficio", placeholder: "🏢"),
        MatchGameItem(id: "banca", italian: "banca", spanish: "banco", imageName: "game_banca", placeholder: "🏦"),
        MatchGameItem(id: "posta", italian: "posta", spanish: "correos", imageName: "game_posta", placeholder: "📮"),
        MatchGameItem(id: "farmacia", italian: "farmacia", spanish: "farmacia", imageName: "game_farmacia", placeholder: "⚕️"),
        MatchGameItem(id: "supermercato", italian: "supermercato", spanish: "supermercado", imageName: "game_supermercato", placeholder: "🛒"),
        MatchGameItem(id: "mercato", italian: "mercato", spanish: "mercado", imageName: "game_mercato", placeholder: "🏪"),
        MatchGameItem(id: "panetteria", italian: "panetteria", spanish: "panadería", imageName: "game_panetteria", placeholder: "🥖"),
        MatchGameItem(id: "biblioteca", italian: "biblioteca", spanish: "biblioteca", imageName: "game_biblioteca", placeholder: "🏛️📚"),
        MatchGameItem(id: "museo", italian: "museo", spanish: "museo", imageName: "game_museo", placeholder: "🏛️🖼️"),
        MatchGameItem(id: "cinema", italian: "cinema", spanish: "cine", imageName: "game_cinema", placeholder: "🎬"),
        MatchGameItem(id: "teatro", italian: "teatro", spanish: "teatro", imageName: "game_teatro", placeholder: "🎭"),
        MatchGameItem(id: "chiesa", italian: "chiesa", spanish: "iglesia", imageName: "game_chiesa", placeholder: "⛪"),
        MatchGameItem(id: "castello", italian: "castello", spanish: "castillo", imageName: "game_castello", placeholder: "🏰"),
        MatchGameItem(id: "palazzo", italian: "palazzo", spanish: "palacio", imageName: "game_palazzo", placeholder: "🏛️👑"),
        MatchGameItem(id: "fabbrica", italian: "fabbrica", spanish: "fábrica", imageName: "game_fabbrica", placeholder: "🏭"),
        MatchGameItem(id: "fattoria", italian: "fattoria", spanish: "granja", imageName: "game_fattoria", placeholder: "🏠🚜"),
        MatchGameItem(id: "palestra", italian: "palestra", spanish: "gimnasio", imageName: "game_palestra", placeholder: "🏋️"),
        MatchGameItem(id: "piscina", italian: "piscina", spanish: "piscina", imageName: "game_piscina", placeholder: "🏊"),
        MatchGameItem(id: "stadio", italian: "stadio", spanish: "estadio", imageName: "game_stadio", placeholder: "🏟️"),
        MatchGameItem(id: "negozio", italian: "negozio", spanish: "tienda", imageName: "game_negozio", placeholder: "🏬"),
        MatchGameItem(id: "bar", italian: "bar", spanish: "bar", imageName: "game_bar", placeholder: "🏠🍸"),
        MatchGameItem(id: "caffetteria", italian: "caffetteria", spanish: "cafetería", imageName: "game_caffetteria", placeholder: "🏠☕"),
        MatchGameItem(id: "discoteca", italian: "discoteca", spanish: "discoteca", imageName: "game_discoteca", placeholder: "🪩"),
        MatchGameItem(id: "universita", italian: "università", spanish: "universidad", imageName: "game_universita", placeholder: "🎓"),
        MatchGameItem(id: "asilo", italian: "asilo", spanish: "guardería", imageName: "game_asilo", placeholder: "🧸"),
        MatchGameItem(id: "caserma", italian: "caserma", spanish: "cuartel", imageName: "game_caserma", placeholder: "🪖"),
        MatchGameItem(id: "prigione", italian: "prigione", spanish: "prisión", imageName: "game_prigione", placeholder: "🔒"),
        MatchGameItem(id: "tribunale", italian: "tribunale", spanish: "juzgado", imageName: "game_tribunale", placeholder: "⚖️"),
        MatchGameItem(id: "municipio", italian: "municipio", spanish: "ayuntamiento", imageName: "game_municipio", placeholder: "🏛️🏙️"),
        MatchGameItem(id: "ambasciata", italian: "ambasciata", spanish: "embajada", imageName: "game_ambasciata", placeholder: "🏛️🌐"),
        MatchGameItem(id: "bosco", italian: "bosco", spanish: "bosque", imageName: "game_bosco", placeholder: "🌲"),
        MatchGameItem(id: "foresta", italian: "foresta", spanish: "selva", imageName: "game_foresta", placeholder: "🌳"),
        MatchGameItem(id: "lago", italian: "lago", spanish: "lago", imageName: "game_lago", placeholder: "🏞️💧"),
        MatchGameItem(id: "fiume", italian: "fiume", spanish: "río", imageName: "game_fiume", placeholder: "🏞️〰️"),
        MatchGameItem(id: "isola", italian: "isola", spanish: "isla", imageName: "game_isola", placeholder: "🏝️"),
        MatchGameItem(id: "deserto", italian: "deserto", spanish: "desierto", imageName: "game_deserto", placeholder: "🏜️"),
        MatchGameItem(id: "cascata", italian: "cascata", spanish: "cascada", imageName: "game_cascata", placeholder: "⛰️💧⬇️"),
        MatchGameItem(id: "zoo", italian: "zoo", spanish: "zoológico", imageName: "game_zoo", placeholder: "🦁🏞️"),
        MatchGameItem(id: "acquario", italian: "acquario", spanish: "acuario", imageName: "game_acquario", placeholder: "🐠"),
        MatchGameItem(id: "giardino", italian: "giardino", spanish: "jardín", imageName: "game_giardino", placeholder: "🌷"),
    ]

    private static let objects: [MatchGameItem] = [
        MatchGameItem(id: "porta", italian: "porta", spanish: "puerta", imageName: "game_porta", placeholder: "🚪"),
        MatchGameItem(id: "chiave", italian: "chiave", spanish: "llave", imageName: "game_chiave", placeholder: "🔑"),
        MatchGameItem(
            id: "tavolo",
            italian: "tavolo",
            spanish: "mesa",
            imageName: "game_tavolo",
            placeholder: "",
            systemImageName: "table.furniture"
        ),
        MatchGameItem(id: "sedia", italian: "sedia", spanish: "silla", imageName: "game_sedia", placeholder: "🪑"),
        MatchGameItem(id: "telefono", italian: "telefono", spanish: "teléfono", imageName: "game_telefono", placeholder: "📱"),
        MatchGameItem(id: "libro", italian: "libro", spanish: "libro", imageName: "game_libro", placeholder: "📕"),
        MatchGameItem(id: "orologio", italian: "orologio", spanish: "reloj", imageName: "game_orologio", placeholder: "⌚️"),
        MatchGameItem(id: "scarpa", italian: "scarpa", spanish: "zapato", imageName: "game_scarpa", placeholder: "👟"),
        MatchGameItem(id: "ombrello", italian: "ombrello", spanish: "paraguas", imageName: "game_ombrello", placeholder: "☂️"),
        MatchGameItem(id: "lampada", italian: "lampada", spanish: "lámpara", imageName: "game_lampada", placeholder: "💡"),
        MatchGameItem(id: "computer", italian: "computer", spanish: "ordenador", imageName: "game_computer", placeholder: "💻"),
        MatchGameItem(id: "tastiera", italian: "tastiera", spanish: "teclado", imageName: "game_tastiera", placeholder: "⌨️"),
        MatchGameItem(id: "mouse", italian: "mouse", spanish: "ratón", imageName: "game_mouse", placeholder: "🖱️"),
        MatchGameItem(id: "schermo", italian: "schermo", spanish: "pantalla", imageName: "game_schermo", placeholder: "🖥️"),
        MatchGameItem(id: "cuffie", italian: "cuffie", spanish: "auriculares", imageName: "game_cuffie", placeholder: "🎧"),
        MatchGameItem(id: "fotocamera", italian: "fotocamera", spanish: "cámara", imageName: "game_fotocamera", placeholder: "📷"),
        MatchGameItem(id: "televisore", italian: "televisore", spanish: "televisor", imageName: "game_televisore", placeholder: "📺"),
        MatchGameItem(id: "radio", italian: "radio", spanish: "radio", imageName: "game_radio", placeholder: "📻"),
        MatchGameItem(id: "penna", italian: "penna", spanish: "bolígrafo", imageName: "game_penna", placeholder: "🖊️"),
        MatchGameItem(id: "matita", italian: "matita", spanish: "lápiz", imageName: "game_matita", placeholder: "✏️"),
        MatchGameItem(id: "quaderno", italian: "quaderno", spanish: "cuaderno", imageName: "game_quaderno", placeholder: "📓"),
        MatchGameItem(id: "foglio", italian: "foglio", spanish: "hoja", imageName: "game_foglio", placeholder: "📄"),
        MatchGameItem(id: "forbici", italian: "forbici", spanish: "tijeras", imageName: "game_forbici", placeholder: "✂️"),
        MatchGameItem(id: "colla", italian: "colla", spanish: "pegamento", imageName: "game_colla", placeholder: "🧴📄"),
        MatchGameItem(id: "righello", italian: "righello", spanish: "regla", imageName: "game_righello", placeholder: "📏"),
        MatchGameItem(id: "bottiglia", italian: "bottiglia", spanish: "botella", imageName: "game_bottiglia", placeholder: "🍾"),
        MatchGameItem(id: "bicchiere", italian: "bicchiere", spanish: "vaso", imageName: "game_bicchiere", placeholder: "🥛"),
        MatchGameItem(id: "tazza", italian: "tazza", spanish: "taza", imageName: "game_tazza", placeholder: "☕"),
        MatchGameItem(id: "piatto", italian: "piatto", spanish: "plato", imageName: "game_piatto", placeholder: "🍽️"),
        MatchGameItem(id: "forchetta", italian: "forchetta", spanish: "tenedor", imageName: "game_forchetta", placeholder: "🍴"),
        MatchGameItem(id: "coltello", italian: "coltello", spanish: "cuchillo", imageName: "game_coltello", placeholder: "🔪"),
        MatchGameItem(id: "cucchiaio", italian: "cucchiaio", spanish: "cuchara", imageName: "game_cucchiaio", placeholder: "🥄"),
        MatchGameItem(id: "pentola", italian: "pentola", spanish: "olla", imageName: "game_pentola", placeholder: "🍲🔥"),
        MatchGameItem(id: "padella", italian: "padella", spanish: "sartén", imageName: "game_padella", placeholder: "🍳"),
        MatchGameItem(id: "frigorifero", italian: "frigorifero", spanish: "frigorífico", imageName: "game_frigorifero", placeholder: "🧊🚪"),
        MatchGameItem(id: "forno", italian: "forno", spanish: "horno", imageName: "game_forno", placeholder: "♨️🍞"),
        MatchGameItem(id: "letto", italian: "letto", spanish: "cama", imageName: "game_letto", placeholder: "🛏️"),
        MatchGameItem(id: "cuscino", italian: "cuscino", spanish: "almohada", imageName: "game_cuscino", placeholder: "🛏️☁️"),
        MatchGameItem(id: "coperta", italian: "coperta", spanish: "manta", imageName: "game_coperta", placeholder: "🛏️🧣"),
        MatchGameItem(id: "specchio", italian: "specchio", spanish: "espejo", imageName: "game_specchio", placeholder: "🪞"),
        MatchGameItem(id: "spazzolino", italian: "spazzolino", spanish: "cepillo de dientes", imageName: "game_spazzolino", placeholder: "🪥"),
        MatchGameItem(id: "sapone", italian: "sapone", spanish: "jabón", imageName: "game_sapone", placeholder: "🧼"),
        MatchGameItem(id: "asciugamano", italian: "asciugamano", spanish: "toalla", imageName: "game_asciugamano", placeholder: "🛁🧺"),
        MatchGameItem(id: "borsa", italian: "borsa", spanish: "bolso", imageName: "game_borsa", placeholder: "👜"),
        MatchGameItem(id: "portafoglio", italian: "portafoglio", spanish: "cartera", imageName: "game_portafoglio", placeholder: "👛💳"),
        MatchGameItem(id: "moneta", italian: "moneta", spanish: "moneda", imageName: "game_moneta", placeholder: "🪙"),
        MatchGameItem(id: "banconota", italian: "banconota", spanish: "billete", imageName: "game_banconota", placeholder: "💵"),
        MatchGameItem(id: "candela", italian: "candela", spanish: "vela", imageName: "game_candela", placeholder: "🕯️"),
        MatchGameItem(id: "martello", italian: "martello", spanish: "martillo", imageName: "game_martello", placeholder: "🔨"),
        MatchGameItem(id: "cacciavite", italian: "cacciavite", spanish: "destornillador", imageName: "game_cacciavite", placeholder: "🪛"),
    ]

    private static let animals: [MatchGameItem] = [
        MatchGameItem(id: "cane", italian: "cane", spanish: "perro", imageName: "game_cane", placeholder: "🐶"),
        MatchGameItem(id: "gatto", italian: "gatto", spanish: "gato", imageName: "game_gatto", placeholder: "🐱"),
        MatchGameItem(id: "cavallo", italian: "cavallo", spanish: "caballo", imageName: "game_cavallo", placeholder: "🐴"),
        MatchGameItem(id: "mucca", italian: "mucca", spanish: "vaca", imageName: "game_mucca", placeholder: "🐮"),
        MatchGameItem(id: "maiale", italian: "maiale", spanish: "cerdo", imageName: "game_maiale", placeholder: "🐷"),
        MatchGameItem(id: "pecora", italian: "pecora", spanish: "oveja", imageName: "game_pecora", placeholder: "🐑"),
        MatchGameItem(id: "leone", italian: "leone", spanish: "león", imageName: "game_leone", placeholder: "🦁"),
        MatchGameItem(id: "elefante", italian: "elefante", spanish: "elefante", imageName: "game_elefante", placeholder: "🐘"),
        MatchGameItem(id: "scimmia", italian: "scimmia", spanish: "mono", imageName: "game_scimmia", placeholder: "🐵"),
        MatchGameItem(id: "pesce", italian: "pesce", spanish: "pez", imageName: "game_pesce", placeholder: "🐟"),
        MatchGameItem(id: "tigre", italian: "tigre", spanish: "tigre", imageName: "game_tigre", placeholder: "🐯"),
        MatchGameItem(id: "giraffa", italian: "giraffa", spanish: "jirafa", imageName: "game_giraffa", placeholder: "🦒"),
        MatchGameItem(id: "zebra", italian: "zebra", spanish: "cebra", imageName: "game_zebra", placeholder: "🦓"),
        MatchGameItem(id: "rinoceronte", italian: "rinoceronte", spanish: "rinoceronte", imageName: "game_rinoceronte", placeholder: "🦏"),
        MatchGameItem(id: "ippopotamo", italian: "ippopotamo", spanish: "hipopótamo", imageName: "game_ippopotamo", placeholder: "🦛"),
        MatchGameItem(id: "orso", italian: "orso", spanish: "oso", imageName: "game_orso", placeholder: "🐻"),
        MatchGameItem(id: "panda", italian: "panda", spanish: "panda", imageName: "game_panda", placeholder: "🐼"),
        MatchGameItem(id: "koala", italian: "koala", spanish: "koala", imageName: "game_koala", placeholder: "🐨"),
        MatchGameItem(id: "canguro", italian: "canguro", spanish: "canguro", imageName: "game_canguro", placeholder: "🦘"),
        MatchGameItem(id: "lupo", italian: "lupo", spanish: "lobo", imageName: "game_lupo", placeholder: "🐺"),
        MatchGameItem(id: "volpe", italian: "volpe", spanish: "zorro", imageName: "game_volpe", placeholder: "🦊"),
        MatchGameItem(id: "coniglio", italian: "coniglio", spanish: "conejo", imageName: "game_coniglio", placeholder: "🐰"),
        MatchGameItem(id: "topo", italian: "topo", spanish: "ratón", imageName: "game_topo", placeholder: "🐭"),
        MatchGameItem(id: "scoiattolo", italian: "scoiattolo", spanish: "ardilla", imageName: "game_scoiattolo", placeholder: "🐿️"),
        MatchGameItem(id: "riccio", italian: "riccio", spanish: "erizo", imageName: "game_riccio", placeholder: "🦔"),
        MatchGameItem(id: "pipistrello", italian: "pipistrello", spanish: "murciélago", imageName: "game_pipistrello", placeholder: "🦇"),
        MatchGameItem(id: "cervo", italian: "cervo", spanish: "ciervo", imageName: "game_cervo", placeholder: "🦌"),
        MatchGameItem(id: "cammello", italian: "cammello", spanish: "camello", imageName: "game_cammello", placeholder: "🐫"),
        MatchGameItem(id: "lama", italian: "lama", spanish: "llama", imageName: "game_lama", placeholder: "🦙"),
        MatchGameItem(id: "gorilla", italian: "gorilla", spanish: "gorila", imageName: "game_gorilla", placeholder: "🦍"),
        MatchGameItem(id: "gallina", italian: "gallina", spanish: "gallina", imageName: "game_gallina", placeholder: "🐔"),
        MatchGameItem(id: "gallo", italian: "gallo", spanish: "gallo", imageName: "game_gallo", placeholder: "🐓"),
        MatchGameItem(id: "anatra", italian: "anatra", spanish: "pato", imageName: "game_anatra", placeholder: "🦆"),
        MatchGameItem(id: "oca", italian: "oca", spanish: "ganso", imageName: "game_oca", placeholder: "🪿"),
        MatchGameItem(id: "tacchino", italian: "tacchino", spanish: "pavo", imageName: "game_tacchino", placeholder: "🦃"),
        MatchGameItem(id: "pinguino", italian: "pinguino", spanish: "pingüino", imageName: "game_pinguino", placeholder: "🐧"),
        MatchGameItem(id: "aquila", italian: "aquila", spanish: "águila", imageName: "game_aquila", placeholder: "🦅"),
        MatchGameItem(id: "gufo", italian: "gufo", spanish: "búho", imageName: "game_gufo", placeholder: "🦉"),
        MatchGameItem(id: "pappagallo", italian: "pappagallo", spanish: "loro", imageName: "game_pappagallo", placeholder: "🦜"),
        MatchGameItem(id: "fenicottero", italian: "fenicottero", spanish: "flamenco", imageName: "game_fenicottero", placeholder: "🦩"),
        MatchGameItem(id: "pavone", italian: "pavone", spanish: "pavo real", imageName: "game_pavone", placeholder: "🦚"),
        MatchGameItem(id: "rana", italian: "rana", spanish: "rana", imageName: "game_rana", placeholder: "🐸"),
        MatchGameItem(id: "coccodrillo", italian: "coccodrillo", spanish: "cocodrilo", imageName: "game_coccodrillo", placeholder: "🐊"),
        MatchGameItem(id: "tartaruga", italian: "tartaruga", spanish: "tortuga", imageName: "game_tartaruga", placeholder: "🐢"),
        MatchGameItem(id: "serpente", italian: "serpente", spanish: "serpiente", imageName: "game_serpente", placeholder: "🐍"),
        MatchGameItem(id: "lucertola", italian: "lucertola", spanish: "lagarto", imageName: "game_lucertola", placeholder: "🦎"),
        MatchGameItem(id: "balena", italian: "balena", spanish: "ballena", imageName: "game_balena", placeholder: "🐳"),
        MatchGameItem(id: "delfino", italian: "delfino", spanish: "delfín", imageName: "game_delfino", placeholder: "🐬"),
        MatchGameItem(id: "squalo", italian: "squalo", spanish: "tiburón", imageName: "game_squalo", placeholder: "🦈"),
        MatchGameItem(id: "polpo", italian: "polpo", spanish: "pulpo", imageName: "game_polpo", placeholder: "🐙"),
    ]
}
